#!/usr/bin/env python3
"""
TapTuxCLISetup
===============
Step 2 of 2 of the bootstrap (step 1 is TapTuxCLISetup.sh, which makes sure
*some* python3 exists just long enough to run this file).

What this does, in order:
  1. Reads TapTuxCLI.json from TapTux-Repository's main branch (or --manifest).
  2. Downloads EVERY archive listed under taptux_cli.requirements - the list is
     never hardcoded here, whatever the manifest names is what gets installed.
  3. Extracts them all into TapTux's private runtime directory
     (~/.taptux/runtime by default; --home / TAPTUX_HOME to move it), so the
     tools TapTuxCLI runs on belong to TapTux alone - nothing is copied from
     or shared with the host's own packages.
  4. Deletes each archive the moment it has been extracted.
  5. Smoke-tests the runtime's own interpreter (ssl, sqlite3, zoneinfo, ...),
     then installs a `taptux` launcher that runs on that interpreter.

After this, the host's python3 is no longer used by TapTux at all.

Re-running is safe: requirements already installed from the same source are
skipped (--force reinstalls everything).

Exit codes: 0 ok, 1 failed, 2 installed but the runtime failed its smoke test.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import sys
from pathlib import Path
from typing import Any, List, Optional

ScriptRoot = Path(__file__).resolve().parent
sys.path.insert(0, str(ScriptRoot))
import TapTuxInstallKit as Kit  # noqa: E402

ManifestFileName = "TapTuxCLI.json"
LauncherMarker = "Generated by TapTuxCLISetup.py"

LauncherTemplate = """#!/bin/sh
# {Marker} - safe to delete; re-run TapTuxCLISetup.py to recreate it.
# Runs TapTux on its own private runtime, never on the host's python.
RUNTIME={Runtime}
TAPTUX_HOME={Home}
export TAPTUX_HOME
unset PYTHONPATH PYTHONSTARTUP PYTHONUSERBASE
PYTHONHOME="$RUNTIME"
export PYTHONHOME
PYTHONNOUSERSITE=1
export PYTHONNOUSERSITE
LD_LIBRARY_PATH="$RUNTIME/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
export LD_LIBRARY_PATH
{CertificateLines}exec "$RUNTIME/bin/python3" {EntryScript} "$@"
"""


def ParseArguments(Argv: Optional[List[str]]) -> argparse.Namespace:
    Parser = argparse.ArgumentParser(
        prog="TapTuxCLISetup.py",
        description="Installs TapTux's core runtime (everything in TapTuxCLI.json's requirements) into a private, isolated directory.",
    )
    Parser.add_argument("--manifest", metavar="PATH_OR_URL", help="use this TapTuxCLI.json (a local file or an https URL) instead of the one in TapTux-Repository")
    Parser.add_argument("--home", metavar="DIR", help=f"TapTux home directory (default: ${Kit.HomeEnvironmentVariable} or ~/.taptux)")
    Parser.add_argument("--arch", metavar="ABI", help="architecture to fetch per-architecture requirements for (default: auto-detected)")
    Parser.add_argument("--force", action="store_true", help="re-download and re-extract requirements even if already installed")
    Parser.add_argument("--no-launcher", action="store_true", help="don't install the `taptux` launcher")
    Parser.add_argument("--skip-verify", action="store_true", help="don't smoke-test the runtime after installing")
    return Parser.parse_args(Argv)


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------

def LoadManifest(Client: Kit.GithubClient, Source: Optional[str]) -> Any:
    if Source and not Source.lower().startswith("https://"):
        try:
            RawText = Path(Source).expanduser().read_text(encoding="utf-8")
        except OSError as Exc:
            raise Kit.InstallError(f"Couldn't read the manifest file: {Exc.strerror}.") from None
    elif Source:
        RawText = Client.FetchTextFromUrl(Source, "TapTuxCLI.json")
    else:
        RawText = Client.FetchRepositoryFile(ManifestFileName, ManifestFileName)
    try:
        return json.loads(RawText)
    except ValueError as Exc:
        raise Kit.InstallError(f"TapTuxCLI.json isn't valid JSON ({Exc}).") from None


def ExtractCliSection(Document: Any) -> dict:
    Section = Document.get("taptux_cli") if isinstance(Document, dict) else None
    if not isinstance(Section, dict):
        raise Kit.InstallError('TapTuxCLI.json is missing its top-level "taptux_cli" object.')
    return Section


# ---------------------------------------------------------------------------
# Launcher
# ---------------------------------------------------------------------------

def IsTermux() -> bool:
    return "/com.termux/" in os.environ.get("PREFIX", "") or os.path.isdir("/data/data/com.termux/files/usr/bin")


def LauncherIsReplaceable(LauncherPath: Path) -> bool:
    """Only overwrite a `taptux` command that's absent, ours, or the one the
    pre-1.0 PythonVendoring wrote - never something the user put there."""
    if not os.path.lexists(LauncherPath):
        return True
    try:
        Text = LauncherPath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return LauncherMarker in Text or "runpy.run_path" in Text


def WriteLauncher(Home: Path, RuntimeRoot: Path) -> List[Path]:
    EntryScript = ScriptRoot / "TapTux.py"
    if not EntryScript.is_file():
        EntryScript = ScriptRoot / "TapTuxCLI.py"

    Bundle = Kit.FindCaBundleFile([RuntimeRoot])
    CertificateLines = ""
    if Bundle is not None:
        CertificateLines = f'if [ -z "${{SSL_CERT_FILE:-}}" ] && [ -z "${{SSL_CERT_DIR:-}}" ]; then SSL_CERT_FILE={shlex.quote(str(Bundle))}; export SSL_CERT_FILE; fi\n'

    Source = LauncherTemplate.format(
        Marker=LauncherMarker,
        Runtime=shlex.quote(str(RuntimeRoot)),
        Home=shlex.quote(str(Home)),
        CertificateLines=CertificateLines,
        EntryScript=shlex.quote(str(EntryScript)),
    )

    Written: List[Path] = []
    PrimaryPath = Home / "bin" / "taptux"
    PrimaryPath.parent.mkdir(parents=True, exist_ok=True)
    PrimaryPath.write_text(Source, encoding="utf-8")
    PrimaryPath.chmod(0o755)
    Written.append(PrimaryPath)

    # A copy on PATH, so plain `taptux` works: Termux's own bin, else ~/.local/bin.
    OnPathDirectory = Path(os.environ.get("PREFIX", "/data/data/com.termux/files/usr")) / "bin" if IsTermux() else Path.home() / ".local" / "bin"
    try:
        OnPathDirectory.mkdir(parents=True, exist_ok=True)
        OnPathPath = OnPathDirectory / "taptux"
        if LauncherIsReplaceable(OnPathPath):
            if os.path.lexists(OnPathPath):
                OnPathPath.unlink()
            OnPathPath.write_text(Source, encoding="utf-8")
            OnPathPath.chmod(0o755)
            Written.append(OnPathPath)
        else:
            print(f"Left the existing {OnPathPath} alone (not written by TapTux). Use {PrimaryPath} instead.")
    except OSError as Exc:
        print(f"Couldn't install `taptux` into {OnPathDirectory} ({Exc.strerror}); use {PrimaryPath} instead.")
    return Written


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def Main(Argv: Optional[List[str]] = None) -> int:
    Arguments = ParseArguments(Argv)
    if sys.version_info < (3, 8):
        print("TapTuxCLISetup needs Python 3.8 or newer to bootstrap.", file=sys.stderr)
        return 1

    Home = Kit.ResolveTapTuxHome(Arguments.home)
    RuntimeRoot = Kit.RuntimeRootFor(Home)
    Architecture = Arguments.arch or os.environ.get("TAPTUX_ARCH") or Kit.DetectArchitecture()

    Token = Kit.LoadGithubToken(Home)
    Client = Kit.GithubClient(Token, Kit.BuildSslContext([RuntimeRoot]))

    print(f"TapTux CLI setup - runtime directory: {RuntimeRoot} (architecture: {Architecture})")
    if not Token and not Arguments.manifest:
        print(f"No GitHub token configured (set {Kit.GithubTokenEnvironmentVariable} or run `taptux cli --set-token`): trying anonymous access.")

    try:
        Section = ExtractCliSection(LoadManifest(Client, Arguments.manifest))
        Requirements = Kit.ParseRequirements(Section.get("requirements"), Architecture)
        if not Requirements:
            print("TapTuxCLI.json lists no requirements - nothing to install.")
        else:
            print(f"TapTux CLI {Section.get('version', '?')}: {len(Requirements)} requirement(s) to install.")
            Kit.InstallRequirements(Client, Requirements, RuntimeRoot, Kit.DownloadsRootFor(Home), Force=Arguments.force)
    except Kit.InstallError as Exc:
        print(f"\nSetup failed: {Exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nInterrupted - anything already extracted is kept; re-run to continue.", file=sys.stderr)
        return 130

    ExitCode = 0
    if Kit.FindRuntimePython(RuntimeRoot) is None:
        print("\nNote: the requirements didn't install a bin/python3, so no launcher was created and TapTux can't run on its own runtime yet.")
        return ExitCode

    if not Arguments.skip_verify:
        print("\nVerifying the private runtime...")
        Failed = 0
        for Label, Passed, Detail in Kit.SmokeTestRuntime(RuntimeRoot):
            print(f"  [{'ok' if Passed else 'FAIL'}] {Label}" + ("" if Passed else f" - {Detail}"))
            Failed += 0 if Passed else 1
        if Failed:
            print(f"\n{Failed} check(s) failed: the runtime is missing a library or module. Make sure TapTuxCLI.json lists every archive the interpreter needs, then re-run with --force.")
            ExitCode = 2

    if not Arguments.no_launcher:
        for LauncherPath in WriteLauncher(Home, RuntimeRoot):
            print(f"Launcher installed: {LauncherPath}")

    print("\nDone. Next: run `taptux cli` to pick and install an environment.")
    return ExitCode


if __name__ == "__main__":
    sys.exit(Main())
